# Run the ephemeris server container. 
version: '3'

services:
    fpga:
        build: 
            context: .
        privileged: true
        volumes:
            - .:/files
        environment:
            - BOARD=tangnano
            - BIN=blinky-tangnano.fs
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "10m"
